"""Add food item indexes

Revision ID: 51b7ae66c421
Revises: d69b756ed65c
Create Date: 2025-01-12 17:06:28.752119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b7ae66c421'
down_revision = 'd69b756ed65c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_item', schema=None) as batch_op:
        batch_op.create_index('idx_food_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('idx_food_type_id', ['food_type_id'], unique=False)
        batch_op.create_index('idx_food_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_item', schema=None) as batch_op:
        batch_op.drop_index('idx_food_user_id')
        batch_op.drop_index('idx_food_type_id')
        batch_op.drop_index('idx_food_timestamp')

    # ### end Alembic commands ###
